KWoC Templates
kossiitkgp/mailing-scripts pull request #5
Opened 2023-07-23 18:28 UTC by manojxplores

2023-07-23 19:53 UTC, proffapt requested changes
- evaluations are not about `project`
- don't hard code the year

2023-07-23 19:53 UTC, proffapt commented on templates/kwoc/mid-eval-reminder.txt
> +This is to remind you about the upcoming mid-evaluation for the project. Please ensure to submit your report by <b>{mid_eval_date}<b>, covering completed tasks and current status.<br><br>
- mid-evaluation is not specific to a project, it's of the student and student can be working on multiple projects
- ther's not such thing like report, they just have to do one commit/PR

2023-07-23 19:53 UTC, proffapt commented on templates/kwoc/end-eval-reminder.txt
> +KWoC 2023 : Final Evaluation Reminder!!
```suggestion
KWoC 2023 : End-Evaluation Reminder!!
```

2023-07-23 19:53 UTC, proffapt commented on templates/kwoc/end-eval-reminder.txt
> +This is to remind you that the final evaluation deadline for the project in the <b>Kharagpur Winter of Code (KWoC)<b> program is fast approaching.<br><br>
```suggestion
This is to remind you that the end-evaluation deadline for <b>Kharagpur Winter of Code (KWoC)<b> program is fast approaching.<br><br>
```

2023-07-23 19:53 UTC, proffapt commented on templates/kwoc/end-eval-reminder.txt
> +Please submit your report by {end_eval_date}, highlighting your progress, achievements, challenges, and suggestions.<br><br>
There is no such thing like report

2023-07-23 19:53 UTC, proffapt commented on templates/kwoc/KWoC is back.txt
> +We hope this email finds you well. We are thrilled to announce that <b>Kharagpur Winter of Code<b> is back this year, and We would like to invite you to be part of this amazing coding extravaganza on
```suggestion
We hope this email finds you well. We are thrilled to announce that <b>Kharagpur Winter of Code<b> is back this year, and we would like to invite you to be part of this amazing coding extravaganza once again!!<br><br>
```

2023-07-23 19:53 UTC, proffapt commented on templates/kwoc/KWoC is back.txt
> +<b>Mark your calenders for KWoC 2023 :<b><br><br>
- Make 2023 the year as a variable, so that we can use it every year

2023-07-24 16:29 UTC, proffapt requested changes
Date bhi toh bataoge mid-evals aur end-evals ki.

2023-07-24 16:29 UTC, proffapt commented on templates/kwoc/mid-eval-reminder.txt
> +Exciting times are ahead as we approach the mid-evaluation phase of Kharagpur Winter of Code (KWoC) 2023! Your journey so far has been remarkable, and we can't wait to see the progress you've made.<b
```suggestion
Exciting times are ahead as we approach the mid-evaluation phase of Kharagpur Winter of Code! Your journey so far has been remarkable, and we can't wait to see the progress you've made.<br><br>
```

2023-07-24 16:29 UTC, proffapt commented on templates/kwoc/mid-eval-reminder.txt
> +This is to remind you about the upcoming mid-evaluation for the project.<br><br>
```suggestion
This is to remind you about the upcoming mid-evaluation.<br><br>
```

2023-08-20 12:08 UTC, harshkhandeparkar commented
@manojxplores please mark the conversations as resolved if you have solved the issues.

2023-08-25 18:53 UTC, proffapt commented
> @manojxplores please mark the conversations as resolved if you have solved the issues.

take updates from him.

2023-08-26 08:54 UTC, harshkhandeparkar requested changes

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/KWoC is back.txt
> +KWoC is back!! : It's time for another exciting coding journey
```suggestion
KWoC is back! It's time for another exciting coding journey.
```

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/KWoC is back.txt
> +We hope this email finds you well. We are thrilled to announce that <b>Kharagpur Winter of Code<b> is back this year, and We would like to invite you to be part of this amazing coding extravaganza on
```suggestion
We hope this email finds you well. We are thrilled to announce that <b>Kharagpur Winter of Code<b> is back this year, and we would like to invite you to be part of this amazing coding extravaganza once again!<br><br>
```

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/KWoC is back.txt
> +Your active involvement in previous editions of KWOC has contributed significantly to its success, and we genuinely appreciate your dedication.<br><br>
```suggestion
Your active involvement in previous editions of KWoC has contributed significantly to its success, and we genuinely appreciate your dedication.<br><br>
```

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/KWoC is back.txt
> +<b>Mark your calenders for KWoC {year} :<b><br><br>
```suggestion
<b>Mark your calenders for KWoC {year}:<b><br><br>
```

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/KWoC is back.txt
> +<i>Registrations for students as well as projects</i> : {date}
```suggestion
<i>Registrations for students as well as projects</i>: {date}
```

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/KWoC is back.txt
> +<i>coding peroid</i>  : {start_date} to {end_date}<br><br>
```suggestion
<i>Coding period</i>: {start_date} to {end_date}<br><br>
```

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/KWoC is back.txt
> +We eagerly anticipate your participation in KWOC {year}. Let's make this edition even more remarkable!
```suggestion
We eagerly anticipate your participation in KWoC {year}. Let's make this edition even more remarkable!
```

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/KWoC is back.txt
> +Stay tuned to our website and social media channels for updates on project selection, mentors, and other important announcements.<br><br>
I think we can add links to the KWoC Slack and Discord here. And maybe even a link to our fb, insta, twitter, and linkedin.

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/KWoC is back.txt
> +
These empty lines seem unnecessary.

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/end-eval-reminder.txt
> +KWoC : End-Evaluation Reminder!!
```suggestion
<b>KWoC End-Evaluation Reminder</b>
```

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/end-eval-reminder.txt
> +We hope this email finds you well. Your hard work and dedication throughout the program have been truly commendable, and we greatly appreciate the efforts you have put into the project<br><br>
```suggestion
We hope this email finds you well. Your hard work and dedication throughout the program have been truly commendable, and we greatly appreciate the efforts you have put into the project.<br><br>
```

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/end-eval-reminder.txt
> +
Same here. Is there any reason for adding these empty lines?

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/end-eval-reminder.txt
> +This is to remind you that the end-evaluation deadline for <b>Kharagpur Winter of Code<b> program is fast approaching. The deadline for the end-evaluation is {end_eval_date}.<br><br>
I think we should mention that the participant should check their dashboard to complete the end evaluation.

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/mid-eval-qualified.txt
> +KWoC : Congratulations on Mid-Evaluation Success!
```suggestion
KWoC: Congratulations on Mid-Evaluation Success!
```

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/mid-eval-qualified.txt
> +Congratulations on your successful mid-evaluation for the project as part of the <b>Kharagpur Winter of Code (KWoC)<b> program!<br><br>
```suggestion
Congratulations on your completing your mid-evaluation in <b>Kharagpur Winter of Code (KWoC) {year}<b> program!<br><br> 
```

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/mid-eval-qualified.txt
> +Thank you for your valuable contributions to the project's progress. Your efforts have been outstanding, and we look forward to your continued excellence in the upcoming phases of the KWoC program.
```suggestion
Thank you for your valuable contributions to the project's progress. Your efforts have been outstanding, and we look forward to your continued excellence in the upcoming phases of the program.
```

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/mid-eval-reminder.txt
> +<b>KWoC <b> : Mid-Evaluation Reminder!!
```suggestion
<b>KWoC: Mid-Evaluation Reminder</b>
```

2023-08-26 08:54 UTC, harshkhandeparkar commented on templates/kwoc/mid-eval-reminder.txt
> +This is to remind you about the upcoming mid-evaluation, which is scheduled to take place on {mid_eval_date}.<br><br>
Again, mention the dashboard.

2023-08-26 12:38 UTC, harshkhandeparkar requested changes

2023-08-26 12:38 UTC, harshkhandeparkar commented on templates/kwoc/KWoC is back.txt
Please remove the spaces in the name of this file. `kwoc-is-back.txt` is better since it will be used in a terminal.

2023-08-28 19:38 UTC, harshkhandeparkar requested changes

2023-08-28 19:38 UTC, harshkhandeparkar commented on templates/kwoc/KWoC-is-back.txt
Keep the filename in all small letters if possible

2023-09-06 16:36 UTC, harshkhandeparkar requested changes

2023-09-06 16:36 UTC, harshkhandeparkar commented on templates/kwoc/KWoC-is-back.txt
Please use only lowercase letters in the filename for consistency.

2023-09-06 16:36 UTC, harshkhandeparkar commented on templates/kwoc/end-eval-disqualified.txt
> +We regret to inform you that your contributions in KWoC were not up to the mark.We appreciate your active participation in the Kharagpur Winter of Code (KWoC) program. Your efforts have not gone unno
```suggestion
We regret to inform you that your contributions in KWoC were not up to the mark. We appreciate your active participation in the Kharagpur Winter of Code (KWoC) program. Your efforts have not gone unnoticed, and we value your dedication to open source development.<br><br>
```

2023-09-06 16:36 UTC, harshkhandeparkar commented on templates/kwoc/end-eval-qualified.txt
> +We hope this message finds you in good spirits.We're delighted to inform you that, you have successfully passed the end evaluations of the Kharagpur Winter of Code {year}.<br><br>
```suggestion
We hope this message finds you in good spirits. We're delighted to inform you that you have successfully passed the end evaluations of the Kharagpur Winter of Code {year}.<br><br>
```

2023-09-06 16:36 UTC, harshkhandeparkar commented on templates/kwoc/end-eval-qualified.txt
> +Once again, congratulations on your successful completion of the Kharagpur Winter of Code.we extend our best wishes for your upcoming pursuits<br><br>
```suggestion
Once again, congratulations on your successful completion of the Kharagpur Winter of Code. We extend our best wishes for your upcoming pursuits.<br><br>
```

2023-09-06 16:36 UTC, harshkhandeparkar commented on templates/kwoc/end-eval-qualified.txt
> +Please find your certificate here: {certificate-link}<br><br>
```suggestion
Please find your certificate here: {certificate_link}<br><br>
```
Best not to use `-`s in variables :)

2023-09-06 16:36 UTC, harshkhandeparkar commented on templates/kwoc/mid-eval-reminder.txt
> +This is to remind you about the upcoming mid-evaluation, which is scheduled to take place on {mid_eval_date}.<br><br>
It would be better to rephrase this as a deadline.

2023-09-11 11:01 UTC, harshkhandeparkar submitted a review, later dismissed

2023-09-12 05:17 UTC, proffapt requested changes
- For disqualified templates it would be great if we can add some motivation links.. like we have during our selection process.. can be those exact same things and maybe some other if you find.
- kwoc-is-back has to be a good full fledged page.. something like this..
   <img width="800" alt="image" src="https://github.com/kossiitkgp/mailing-scripts/assets/86282911/cd691bcd-550b-46b5-8c35-afff9c5613f8">

2023-09-12 05:17 UTC, proffapt commented on templates/kwoc/mid-eval-reminder.txt
> +<em>Keep up the excellent work, and let's make this mid-evaluation a success to remember!<em>
Add this into end eval reminder..

2023-09-12 06:46 UTC, harshkhandeparkar commented on templates/kwoc/mid-eval-reminder.txt
> +<em>Keep up the excellent work, and let's make this mid-evaluation a success to remember!<em>
Usme hai sir

2023-09-12 08:53 UTC, proffapt commented on templates/kwoc/mid-eval-reminder.txt
> +<em>Keep up the excellent work, and let's make this mid-evaluation a success to remember!<em>
aaahh, ok then

2023-10-26 14:15 UTC, harshkhandeparkar commented
Should we convert all templates to html files? @proffapt ?

2023-10-26 14:32 UTC, harshkhandeparkar requested changes

2023-10-26 14:32 UTC, harshkhandeparkar commented on templates/kwoc/kwoc-is-back.html
> +                    <h2 style="text-align: center; font-family: 'Roboto', sans-serif;"><b>Is Back !!</b></h2>
```suggestion
                    <h2 style="text-align: center; font-family: 'Roboto', sans-serif;"><b>Is Back!</b></h2>
```

2023-10-26 14:32 UTC, harshkhandeparkar commented on templates/kwoc/kwoc-is-back.html
> +                    that Kharagpur Winter
Why are there newlines here?

2023-10-26 14:32 UTC, harshkhandeparkar commented on templates/kwoc/kwoc-is-back.html
> +                <p style="margin: 0; margin-bottom: 1rem;">coding peroid: {start_date} to {end_date}</p>
```suggestion
                <p style="margin: 0; margin-bottom: 1rem;"><b>Coding period</b>: {start_date} to {end_date}</p>
```

2023-10-26 14:32 UTC, harshkhandeparkar commented on templates/kwoc/kwoc-is-back.html
> +                <p style="margin: 0;">Registrations for students as well as projects: {date}</p>
```suggestion
                <p style="margin: 0;"><b>Registrations for students as well as projects</b>: {date}</p>
```

2023-10-26 14:32 UTC, harshkhandeparkar commented on templates/kwoc/kwoc-is-back.html
> +                    once again</p>
```suggestion
                    once again.</p>
```

2023-10-30 10:12 UTC, proffapt commented
> Should we convert all templates to html files? @proffapt ?

They are already HTML right?
If you mean like such bg and stuff.. if there is time then isse behtar kya hoga..

2023-10-30 12:18 UTC, harshkhandeparkar commented
> > Should we convert all templates to html files? @proffapt ?
> 
> They are already HTML right? If you mean like such bg and stuff.. if there is time then isse behtar kya hoga..

Mera matlab tha `.html` daal dete hain sab mein.

2023-10-30 12:18 UTC, harshkhandeparkar commented
Also haan, baaki KWoC related templates mein bg daal dete hain.

2023-11-02 16:12 UTC, proffapt commented
> Mera matlab tha .html daal dete hain sab mein.

Pehle itna hi karlo, kuch farak nahi padta anyhow. It should just work in the starting.

2023-11-07 13:17 UTC, harshkhandeparkar requested changes, later dismissed
check slack @manojxplores

2023-11-29 06:27 UTC, closed without merging